name: "[Epic] New Feature Category"
description: "Define a major functionality area for FlactanCLI"
title: "[Epic] <Epic Title>"
labels: ["Epic"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📌 Epic Description
        _Provide a high-level description of this Epic._

  - type: textarea
    id: goals
    attributes:
      label: "🎯 Goals"
      description: "List the primary objectives for this Epic."
      placeholder: |
        - Goal 1
        - Goal 2
        - Goal 3
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: "📂 Features Under This Epic"
      description: "List the features that fall under this Epic."
      placeholder: |
        - [ ] Feature 1
        - [ ] Feature 2
        - [ ] Feature 3
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: "🔗 Related Issues / PRs"
      description: "Link any related issues or pull requests."
      placeholder: "#123, #456"

  - type: dropdown
    id: priority
    attributes:
      label: "🔥 Priority"
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
