name: Release Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'feature/') || startsWith(github.event.pull_request.head.ref, 'fix/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Ensures it runs on the `main` branch

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          echo "TAG=$(git tag --sort=-v:refname | head -n 1)" >> $GITHUB_ENV

      - name: Verify Tag
        run: echo "Latest tag is ${{ env.TAG }}"

      - name: Build and Upload Artifacts
        run: |
          make build-linux
          make build-windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flactanCLI-artifacts
          path: bin/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          body: "🚀 New Release: ${{ env.TAG }}\n\nChanges:\n- Auto-generated release from GitHub Actions\n${{ env.PR_BODY }}"
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
