name: Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          make build-linux
          make build-windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flactanCLI-artifacts
          path: bin/*

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: flactanCLI-artifacts
          path: bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "🚀 New Release: ${{ github.ref_name }}\n\nChanges:\n- Auto-generated release from GitHub Actions"
          files: bin/*
